//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public Auto()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int id { get; set; }
        public string patente { get; set; }
        public int km { get; set; }
        public string nro_motor { get; set; }
        public int id_modelo { get; set; }
        public string nro_chasis { get; set; }
        public int id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
