//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Auto = new HashSet<Auto>();
            this.Repuesto_Modelo = new HashSet<Repuesto_Modelo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int anio { get; set; }
        public int id_marca { get; set; }
    
        public virtual ICollection<Auto> Auto { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual ICollection<Repuesto_Modelo> Repuesto_Modelo { get; set; }
    }
}
