//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Repuestos2Entities4 : DbContext
    {
        public Repuestos2Entities4()
            : base("name=Repuestos2Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auto> Auto { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Detalle_Servicio> Detalle_Servicio { get; set; }
        public DbSet<Estado_Servicio> Estado_Servicio { get; set; }
        public DbSet<img_reporte> img_reporte { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Modelo> Modelo { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Reporte> Reporte { get; set; }
        public DbSet<Repuesto> Repuesto { get; set; }
        public DbSet<Repuesto_Modelo> Repuesto_Modelo { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
