//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto
    {
        public Repuesto()
        {
            this.Detalle_Servicio = new HashSet<Detalle_Servicio>();
            this.Repuesto_Modelo = new HashSet<Repuesto_Modelo>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int id { get; set; }
        public string sku { get; set; }
        public string descripcion { get; set; }
        public int id_modelo { get; set; }
        public int id_tipo { get; set; }
        public decimal valor_neto { get; set; }
    
        public virtual ICollection<Detalle_Servicio> Detalle_Servicio { get; set; }
        public virtual ICollection<Repuesto_Modelo> Repuesto_Modelo { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
