//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Detalle_Servicio = new HashSet<Detalle_Servicio>();
            this.Reporte = new HashSet<Reporte>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public decimal valor_neto { get; set; }
        public decimal valor_iva { get; set; }
        public decimal valor_total { get; set; }
        public bool cancelado { get; set; }
        public int id_sucursal { get; set; }
        public int id_usuario { get; set; }
        public int id_auto { get; set; }
        public decimal mano_obra { get; set; }
        public string repuesto { get; set; }
        public int id_estado { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual ICollection<Detalle_Servicio> Detalle_Servicio { get; set; }
        public virtual Estado_Servicio Estado_Servicio { get; set; }
        public virtual ICollection<Reporte> Reporte { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
