//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id { get; set; }
        public int cantidad { get; set; }
        public int id_sucursal { get; set; }
        public int id_repuesto { get; set; }
    
        public virtual Repuesto Repuesto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
