//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Repuestos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Logs = new HashSet<Logs>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int id { get; set; }
        public int rut { get; set; }
        public string dv { get; set; }
        public string correo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int telefono { get; set; }
        public int id_perfil { get; set; }
        public string direccion { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
